#==================================================================#
#     ╔═══╗╔═══╗╔═══╕╔═══╗╒══╬══╕┍╍╥╍┑╔═══╗    ╊    ╌╍╁╍╌┠┤        #
#     ║ █▌ ║ ▒ ║║___ ║ ▒ ║   ║    ┎╫┒ ║ ▓ ║    ╏      ╏  ┣╍╍╍┓     #
#     ║ █▌ ╠══╦╝║ˉˉˉˉ╟╍╍╍╢   ╏    ┖╫┚ ║ ▓ ║    ╏      ╏  ╏ ▒ ╏     #
#     ╚═══╝║  ╬═╚═══╛╜   ╙   ╎   ┕╍╨╍┙╚═══╝    ╄╍╍╍╃┍╍┻╍┑╄╍╍╍┩     #
#==================================================================#
#                        Main Configuration                        #
#==================================================================#

#DON'T TOUCH THIS!
version: 2

#Language
language: en_US

#Update Checker
enable_update_checker: true

#Metrics, which collects anonymous data for developers.
enable_metrics: true


