name: CreatioLib
version: 0.1.02-alpha
main: com.henryrenyz.creatiolib.Creatio
api-version: 1.13
softdepend: [Skript, CoreProtect, ProtocolLib]
authors: [HenryRenYz]
description: A small lib for utilities
commands:
  creatio:
    description: Main Command
    usage: /<command>
    permission: <plugin name>.basic
    permission-message: You're not permitted to do this!